from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum
import uuid

class MemoryType(Enum):
    EPISODIC = "episodic"   
    SEMANTIC = "semantic"   

class EntityType(Enum):
    PERSON = "person"
    OBJECT = "object"
    TEXT = "text" 

@dataclass(kw_only=True)
class BaseObservation:
    """Base fields for anything captured from the video stream."""
    video_id: str
    clip_id: int
    ts_ms: int
    # default_factory makes this a 'default argument'
    obs_id: str = field(default_factory=lambda: str(uuid.uuid4()))

@dataclass(kw_only=True)
class FaceObservation(BaseObservation):
    """A raw face detection before identity resolution."""
    embedding: List[float]
    bbox: List[int]
    base64_img: str
    detection_score: float
    quality_score: float
    entity_id: Optional[str] = None 

@dataclass(kw_only=True)
class VoiceObservation(BaseObservation):
    """A raw snippet of speech."""
    embedding: List[float]
    asr_text: str
    start_sec: float
    end_sec: float
    entity_id: Optional[str] = None

@dataclass(kw_only=True)
class VisualObservation(BaseObservation):
    """Global frame context (SigLIP + OCR + Objects)."""
    clip_embedding: List[float]
    ocr_tokens: List[Dict[str, Any]]
    detected_objects: List[str]
    spatial_metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass(kw_only=True)
class MemoryNode:
    """A high-level thought or description generated by the agent."""
    video_id: str
    content: str
    mem_type: MemoryType
    embedding: Optional[List[float]] = None
    clip_id: Optional[int] = None
    mem_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    linked_entities: List[str] = field(default_factory=list)

@dataclass(kw_only=True)
class GlobalEntity:
    """A unique Person or Object tracked across the entire video."""
    entity_id: str
    entity_type: EntityType
    video_id: str
    canonical_name: Optional[str] = None
    attributes: Dict[str, Any] = field(default_factory=dict)
    face_embeddings: List[List[float]] = field(default_factory=list)
    voice_embeddings: List[List[float]] = field(default_factory=list)